import { CODING_EXTRA } from "./coding-bank-extra.ts";
export type CodingDifficulty = "easy" | "medium" | "hard";

export type CodingProblem = {
  key: string;
  difficulty: CodingDifficulty;
  title: string;
  prompt: string;
};

function problem(
  key: string,
  difficulty: CodingDifficulty,
  title: string,
  signature: string,
  task: string,
  example: string,
): CodingProblem {
  return {
    key,
    difficulty,
    title,
    prompt: `${title}

Write \`${signature}\`.

${task}

Example
${example}

Use the language of the editor. A correct result for the stated rules is what a reviewer grades. State the approach in a short comment if the code is not obvious. These prompts were written for this bank. They are not items from another site.`,
  };
}

/** Original easy, medium, and hard coding prompts. Not copied from a public problem set. */
export const CODING_BANK: readonly CodingProblem[] = [
  problem("warehouse-pair", "medium", "Crate pair", "cratePair(weights: number[], capacity: number): [number, number] | null",
    "Return the indexes of two different crates whose weights add up to capacity. If several pairs work, return the one with the smaller first index, then the smaller second index. Return null when none exist.",
    "cratePair([4, 7, 1, 8, 3], 11) returns [1, 4] because 7 + 3 = 11."),
  problem("ferry-window", "medium", "Ferry window", "longestFerry(weights: number[], limit: number): number",
    "A ferry can take a contiguous line of passengers. Return the largest number of people in a row whose weights sum to at most limit. An empty line returns 0.",
    "longestFerry([2, 3, 1, 4, 2], 6) returns 3."),
  problem("shelf-search", "medium", "Rotated shelf", "findCallNumber(shelf: number[], call: number): number",
    "The shelf was sorted, then rotated left by an unknown amount. Return the index of call, or -1. Values are unique.",
    "findCallNumber([40, 50, 10, 20, 30], 20) returns 3."),
  problem("badge-streak", "medium", "Badge streak", "longestStreak(days: number[]): number",
    "days holds unique check-in day numbers. Return the length of the longest run of consecutive days. Order in the input does not matter.",
    "longestStreak([8, 1, 3, 2, 11, 4]) returns 4."),
  problem("delivery-windows", "medium", "Merge delivery windows", "mergeWindows(windows: [number, number][]): [number, number][]",
    "Each window is [start, end), with start < end. Merge overlaps and touching windows. Return the result sorted by start.",
    "mergeWindows([[1, 4], [4, 6], [10, 12], [5, 8]]) returns [[1, 8], [10, 12]]."),
  problem("station-codes", "medium", "Station codes", "longestClear(signal: string): number",
    "A signal is a string of station codes, one character each. Return the length of the longest substring that does not repeat a code.",
    "longestClear('abbaec') returns 3."),
  problem("holding-stack", "medium", "Holding stack", "canUnload(target: number[]): boolean",
    "Cars arrive numbered 1 through n in that order. You may send a car straight to the output or park it on one stack (last in, first out). Return whether target, a permutation of 1..n, can be produced.",
    "canUnload([1, 3, 2]) returns true. canUnload([3, 1, 2]) returns false."),
  problem("meter-except", "medium", "Meter except self", "meterExcept(readings: number[]): number[]",
    "Return an array where each position is the product of every other reading. Do not use division. A single reading returns [1].",
    "meterExcept([2, 3, 4]) returns [12, 8, 6]."),
  problem("next-shift", "medium", "Next richer shift", "nextRicher(pay: number[]): number[]",
    "For each shift, return the pay of the next strictly higher shift to its right. If none exists, use -1.",
    "nextRicher([4, 2, 5, 3]) returns [5, 5, -1, -1]."),
  problem("bin-codes", "medium", "Three bins", "sortBins(codes: number[]): number[]",
    "codes contains only 0, 1, and 2. Return the same values sorted ascending. You may mutate the input.",
    "sortBins([2, 0, 1, 2, 0]) returns [0, 0, 1, 2, 2]."),
  problem("booth-change", "medium", "Booth change", "fewestCoins(coins: number[], amount: number): number",
    "coins are positive denominations you may use any number of times. Return the fewest coins that sum to amount, or -1 if it is impossible. amount 0 returns 0.",
    "fewestCoins([1, 3, 4], 6) returns 2."),
  problem("label-groups", "medium", "Label groups", "groupLabels(labels: string[]): string[][]",
    "Group labels that use the same letters with the same counts. Order inside a group follows the input. Order of groups follows the first label in each group.",
    "groupLabels(['tap', 'pat', 'top', 'apt']) returns [['tap', 'pat', 'apt'], ['top']]."),
  problem("dock-distance", "medium", "Nearest docks", "nearestDocks(points: [number, number][], k: number): [number, number][]",
    "points are dock coordinates. Return the k closest to (0, 0) by squared distance, ties broken by the earlier input. k is between 1 and the number of points.",
    "nearestDocks([[1, 2], [2, 1], [0, 1]], 2) returns [[0, 1], [1, 2]]."),
  problem("room-count", "medium", "Room count", "roomsNeeded(meetings: [number, number][]): number",
    "Each meeting is [start, end). A room frees at end. Return the minimum number of rooms so no two meetings share a room while both are open.",
    "roomsNeeded([[0, 30], [5, 10], [15, 20]]) returns 2."),
  problem("digit-ways", "medium", "Digit ways", "decodeWays(digits: string): number",
    "A message maps 1..26 to letters. Return how many ways digits can be decoded. A leading zero in a piece is invalid. An empty string returns 0.",
    "decodeWays('226') returns 3."),
  problem("module-order", "medium", "Module order", "moduleOrder(n: number, edges: [number, number][]): number[] | null",
    "There are modules 0..n-1. Each edge [before, after] means before must precede after. Return any valid order, or null if the graph has a cycle.",
    "moduleOrder(3, [[0, 1], [1, 2]]) returns [0, 1, 2]."),
  problem("orchard-plots", "medium", "Orchard plots", "ripePlots(grid: number[][]): number",
    "grid holds 1 for a ripe tree and 0 for empty soil. Trees touching on an edge (not a corner) form one plot. Return the number of plots.",
    "ripePlots([[1, 1, 0], [0, 1, 0], [0, 0, 1]]) returns 2."),
  problem("floor-spiral", "medium", "Floor spiral", "spiralWalk(plan: number[][]): number[]",
    "Walk a rectangular grid clockwise from the top-left and return the cells in that order. An empty grid returns [].",
    "spiralWalk([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) returns [1, 2, 3, 6, 9, 8, 7, 4, 5]."),
  problem("digit-lists", "medium", "Digit lists", "addDigitLists(a: number[], b: number[]): number[]",
    "a and b are digits of non-negative integers, most significant digit first, with no leading zero unless the value is 0. Return their sum in the same form.",
    "addDigitLists([9, 9], [1]) returns [1, 0, 0]."),
  problem("window-max", "medium", "Window maximum", "windowMax(values: number[], k: number): number[]",
    "Return the maximum of every contiguous window of length k. k is between 1 and values.length.",
    "windowMax([1, 3, -1, -3, 5, 3], 3) returns [3, 3, 5, 5]."),
  problem("ticket-k", "medium", "First unique in a window", "firstUnique(stream: string, k: number): string",
    "Look at each window of k characters. Return a string of the first character in that window that appears once inside it. If a window has none, put '.'.",
    "firstUnique('aabbac', 3) returns '.b.c'."),
  problem("shift-profit", "medium", "Shift profit", "bestShiftProfit(prices: number[]): number",
    "prices[i] is the rate on day i. You may buy once and sell once later. Return the largest profit, or 0 if no gain is possible.",
    "bestShiftProfit([7, 1, 5, 3, 6, 4]) returns 5."),
  problem("ladder-steps", "medium", "Ladder steps", "climbWays(n: number, steps: number[]): number",
    "You can climb n rungs. On each move you advance by one of the values in steps. Order matters. Return the number of ways. n = 0 returns 1.",
    "climbWays(4, [1, 2]) returns 5."),
  problem("cache-line", "medium", "Small cache", "runCache(capacity: number, ops: ['get' | 'put', number, number?][]): (number | null)[]",
    "Simulate a cache that keeps at most capacity keys and evicts the least recently used key. get returns the value or null. put stores key to value and counts as a use. Return the get results only.",
    "runCache(2, [['put', 1, 1], ['put', 2, 2], ['get', 1], ['put', 3, 3], ['get', 2]]) returns [1, null]."),
  problem("grid-minutes", "medium", "Grid minutes", "minutesToGate(grid: number[][]): number",
    "0 is open floor, 1 is a wall. Start at the top-left and stop at the bottom-right. Moving up, down, left, or right costs one minute. Return the fewest minutes, or -1 if the gate is unreachable.",
    "minutesToGate([[0, 0, 1], [1, 0, 0], [1, 0, 0]]) returns 4."),

  problem("serial-distance", "hard", "Serial distance", "serialDistance(a: string, b: string): number",
    "Return the minimum insertions, deletions, and substitutions that turn a into b. Each edit costs 1.",
    "serialDistance('kitten', 'sitting') returns 3."),
  problem("roof-water", "hard", "Roof water", "roofWater(heights: number[]): number",
    "heights are bar heights in a row. Water settles in the gaps up to the lower bounding bar. Return how many units of water the row holds.",
    "roofWater([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) returns 6."),
  problem("delay-median", "hard", "Delay median", "delayMedian(a: number[], b: number[]): number",
    "a and b are sorted ascending. Return the median of the combined multiset. If the count is even, return the average of the two middle values.",
    "delayMedian([1, 3], [2]) returns 2."),
  problem("badge-cover", "hard", "Badge cover", "shortestCover(log: string, need: string): string",
    "Return the shortest contiguous slice of log that contains every character in need, with at least the required counts. If several are the same length, return the leftmost. If none exist, return ''.",
    "shortestCover('adobecodeban', 'abc') returns 'ban'."),
  problem("free-rectangle", "hard", "Free rectangle", "largestFree(grid: number[][]): number",
    "1 is a free cell and 0 is blocked. Return the area of the largest rectangle of free cells. A single free cell has area 1.",
    "largestFree([[1, 0, 1], [1, 1, 1], [1, 1, 0]]) returns 4."),
  problem("pattern-match", "hard", "Simple pattern", "matchesPattern(text: string, pattern: string): boolean",
    "pattern may contain letters, '.' which matches one character, and '*' which repeats the previous pattern character zero or more times. '*' is never first and never doubled. Return whether the whole text matches.",
    "matchesPattern('aab', 'c*a*b') returns true."),
  problem("burst-order", "hard", "Burst order", "bestBurst(scores: number[]): number",
    "Crates in a line have scores. Bursting crate i earns the product of its neighbors' scores (missing neighbors count as 1) and removes it. Return the best total.",
    "bestBurst([3, 1, 5]) returns 35."),
  problem("cut-palindromes", "hard", "Palindrome cuts", "minPalindromeCuts(label: string): number",
    "Return the fewest cuts that split label into pieces that are each a palindrome. A palindrome needs zero cuts.",
    "minPalindromeCuts('aab') returns 1."),
  problem("weave-codes", "hard", "Weave codes", "canWeave(a: string, b: string, woven: string): boolean",
    "Return whether woven is an interleaving of a and b that preserves the order of each. Characters are drawn from one string or the other.",
    "canWeave('ab', 'cd', 'acbd') returns true. canWeave('ab', 'cd', 'adbc') returns false."),
  problem("critical-links", "hard", "Critical links", "criticalLinks(n: number, edges: [number, number][]): [number, number][]",
    "An undirected network has nodes 0..n-1. Return every edge whose removal increases the number of connected components. List each edge with the smaller node first, and sort the list.",
    "criticalLinks(4, [[0, 1], [1, 2], [2, 0], [1, 3]]) returns [[1, 3]]."),
  problem("queen-count", "hard", "Quiet boards", "quietBoards(n: number): number",
    "Count ways to place n queens on an n by n board so no two share a row, column, or diagonal. Rotations count as different.",
    "quietBoards(4) returns 2."),
  problem("envelope-stack", "hard", "Envelope stack", "tallestStack(envelopes: [number, number][]): number",
    "Each envelope is [width, height]. One fits in another only when both width and height are strictly smaller. Return the most envelopes in one nested stack.",
    "tallestStack([[5, 4], [6, 4], [6, 7], [2, 3]]) returns 3."),
  problem("smaller-after", "hard", "Smaller after", "smallerAfter(values: number[]): number[]",
    "For each index, return how many later values are strictly smaller.",
    "smallerAfter([5, 2, 6, 1]) returns [2, 1, 1, 0]."),
  problem("cooldown-profit", "hard", "Cooldown profit", "cooldownProfit(prices: number[]): number",
    "You may complete as many buy-then-sell trades as you want. After a sale you must skip the next day. Return the best profit.",
    "cooldownProfit([1, 2, 3, 0, 2]) returns 3."),
  problem("grid-eliminations", "hard", "Obstacle budget", "shortestWithBudget(grid: number[][], budget: number): number",
    "0 is open and 1 is an obstacle. You may pass through at most budget obstacles. Return the fewest steps from the top-left to the bottom-right, or -1.",
    "shortestWithBudget([[0, 1, 0], [0, 1, 0], [0, 0, 0]], 1) returns 4."),
  problem("bus-hops", "hard", "Bus hops", "fewestBuses(routes: number[][], source: number, target: number): number",
    "routes[i] is the set of stops one bus visits. You may ride a bus between any of its stops. Return the fewest buses to go from source to target, or -1. Staying put when source equals target returns 0.",
    "fewestBuses([[1, 2, 7], [3, 6, 7]], 1, 6) returns 2."),
  problem("cherry-rows", "hard", "Two pickers", "bestCherries(grid: number[][]): number",
    "Two pickers start at the top-left and top-right of a grid of non-negative values and both must end on the bottom row. Each move steps down one row and may change column by -1, 0, or 1, staying inside the grid. A cell claimed by both on the same row counts once. Return the best total.",
    "bestCherries([[3, 1, 1], [2, 5, 1], [1, 5, 5], [2, 1, 1]]) returns 24."),
  problem("word-ladder-len", "hard", "Code ladder", "ladderLength(begin: string, end: string, bank: string[]): number",
    "Each step changes exactly one character and must land on a word in bank. Return the number of words in the shortest sequence from begin to end, counting both, or 0 if end is unreachable. begin does not have to be in bank.",
    "ladderLength('hit', 'cog', ['hot', 'dot', 'dog', 'lot', 'log', 'cog']) returns 5."),
  problem("alien-order", "hard", "Badge alphabet", "badgeOrder(words: string[]): string | null",
    "words are sorted in an unknown alphabet. Return any letter order that makes that sort valid, or null if the list contradicts itself. Letters that never appear are omitted.",
    "badgeOrder(['wrt', 'wrf', 'er', 'ett', 'rftt']) returns a string such as 'wertf'."),
  problem("split-words", "hard", "Dictionary split", "allSplits(text: string, words: string[]): string[][]",
    "Return every way to split text into a sequence of words from the dictionary, preserving order. The dictionary has no duplicates. Order the results by the input scan.",
    "allSplits('catsanddog', ['cat', 'cats', 'and', 'sand', 'dog']) returns [['cat', 'sand', 'dog'], ['cats', 'and', 'dog']]."),
  problem("max-path-sum", "hard", "Path sum", "bestPath(grid: number[][]): number",
    "Move only right or down from the top-left to the bottom-right. Cells may be negative. Return the best path sum.",
    "bestPath([[1, -2], [3, 4]]) returns 8."),
  problem("job-schedule", "hard", "Job schedule", "maxJobProfit(jobs: { start: number; end: number; profit: number }[]): number",
    "A person can do one job at a time. Jobs include start and exclude end. Return the maximum profit of a compatible subset.",
    "maxJobProfit([{ start: 1, end: 3, profit: 20 }, { start: 2, end: 5, profit: 20 }, { start: 4, end: 6, profit: 30 }]) returns 50."),
  problem("restore-addresses", "hard", "Restore addresses", "restoreAddresses(digits: string): string[]",
    "Return every way to insert three dots so the string becomes four decimal parts. Each part is 0 through 255 with no leading zero. Order follows the input.",
    "restoreAddresses('25525511135') returns ['255.255.11.135', '255.255.111.35']."),
  problem("calc-basic", "hard", "Basic calculator", "basicCalc(expr: string): number",
    "expr contains non-negative integers, '+', '-', '*', '/', spaces, and parentheses. '*' and '/' bind tighter than '+' and '-'. Division truncates toward zero. Return the value.",
    "basicCalc('2*(3+4) - 6/2') returns 11."),
  problem("skyline", "hard", "Skyline", "skyline(buildings: [number, number, number][]): [number, number][]",
    "Each building is [left, right, height], with left < right. Return the skyline as [x, height] points where the running height changes, from left to right.",
    "skyline([[2, 9, 10], [3, 7, 15], [5, 12, 12]]) returns [[2, 10], [3, 15], [7, 12], [12, 0]]."),
  ...CODING_EXTRA,
];
