/**
 * Spanish (primary) copy for the RECRUIT4US website.
 *
 * Every product statement here is traced in docs/marketing-claims.md.
 * `npm run claims` scans this file (and every other file under src/) for
 * forbidden phrasings (AI decides, auto-reject, hosted video, LinkedIn, ...).
 * Keep sentence case, plain verbs, no hype.
 */

export const es = {
  meta: {
    lang: "es",
    siteName: "RECRUIT4US",
    titleSuffix: "RECRUIT4US",
    description:
      "RECRUIT4US es el espacio de contratación de tu empresa: vacantes, postulaciones, pipeline, evaluaciones, entrevistas y ofertas. El sistema reúne la evidencia; las personas deciden.",
  },

  a11y: {
    skip: "Saltar al contenido",
    demoData: "Datos de demostración",
    illustration: "Ilustración",
  },

  nav: {
    primary: "Navegación principal",
    dock: "Recorrido de la página",
    menu: "Menú",
    close: "Cerrar menú",
    signIn: "Ingresar",
    demo: "Solicitar demo",
    how: "Ver cómo funciona",
    themeDay: "Día",
    themeNight: "Noche",
    themeLabel: "Cambiar a modo noche",
    themeLabelDark: "Cambiar a modo día",
    home: "Inicio",
    items: [
      { id: "inicio", label: "Inicio" },
      { id: "vacantes", label: "Vacantes" },
      { id: "pipeline", label: "Pipeline" },
      { id: "evaluaciones", label: "Evaluaciones" },
      { id: "entrevistas", label: "Entrevistas" },
      { id: "ofertas", label: "Ofertas" },
      { id: "confianza", label: "Confianza" },
      { id: "demo", label: "Demo" },
    ],
    pages: [
      { href: "/seguridad", label: "Seguridad y privacidad" },
      { href: "/integraciones", label: "Integraciones" },
      { href: "/contacto", label: "Contacto" },
    ],
  },

  hero: {
    lines: ["Cada paso", "de la contratación,", "con evidencia", "a la vista."],
    lede:
      "RECRUIT4US es el espacio de contratación de tu empresa: vacantes, postulaciones, pipeline, evaluaciones, entrevistas y ofertas en un solo lugar. El sistema reúne la evidencia. Las personas deciden.",
    stages: ["Descubrir", "Postular", "Filtrar", "Evaluar", "Entrevistar", "Revisar", "Ofertar", "Incorporar"],
    sceneLabel:
      "Ilustración: trayectorias de candidatos avanzan entre cuatro puertas, una por cada chevrón del logo. Algunas se detienen en una revisión humana; ninguna es descartada por el sistema.",
    scroll: "Recorre la página",
  },

  whatIs: {
    title: "Un espacio de contratación para cada empresa.",
    body:
      "Cada empresa trabaja en su propio espacio. Sus vacantes, candidatos, evaluaciones y notas quedan separados de los de cualquier otra empresa, y cada persona del equipo ve el mismo recorrido.",
    hint: "Pasa el cursor o toca un módulo para ver la pantalla real.",
    modules: [
      {
        id: "careers",
        name: "Vacantes y página de empleo",
        text: "Publica una vacante, recibe postulaciones con comprobante y muestra el formulario dentro de tu propio sitio.",
        shot: "careers",
      },
      {
        id: "pipeline",
        name: "Pipeline",
        text: "Etapas visibles, notas, etiquetas y exportación CSV. Una persona mueve cada postulación.",
        shot: "pipeline",
      },
      {
        id: "assess",
        name: "Evaluaciones",
        text: "Bancos de preguntas, guardado automático, fecha límite en el servidor y comprobante al enviar.",
        shot: "assessment-attempt",
      },
      {
        id: "interview",
        name: "Entrevistas",
        text: "Agenda, sala en vivo para código y scorecards que se bloquean al enviarse.",
        shot: "scorecard",
      },
      {
        id: "offers",
        name: "Ofertas",
        text: "La oferta llega al portal del candidato. Al aceptarla se abren las tareas de incorporación.",
        shot: "offers",
      },
    ],
  },

  journey: {
    title: "Lo que registra el sistema y lo que decide tu equipo.",
    intro:
      "Cada etapa deja evidencia. Ninguna etapa toma la decisión por ti. Así se reparte el trabajo en RECRUIT4US.",
    records: "Registra RECRUIT4US",
    decides: "Decide tu equipo",
    progress: "Etapa",
    stages: [
      {
        name: "Atraer",
        records: "La vacante publicada, su página de empleo y el formulario que puedes insertar en tu sitio.",
        decides: "Qué vacante se publica, cuándo y con qué preguntas.",
      },
      {
        name: "Postular",
        records: "Nombre, correo, respuestas y CV, con un comprobante para el candidato.",
        decides: "Los criterios eliminatorios explícitos: años mínimos y autorización de trabajo.",
      },
      {
        name: "Filtrar",
        records: "Las palabras imprescindibles de la vacante encontradas en el CV, y los campos indexados.",
        decides: "A quién avanzar. El filtro de CV cuenta evidencia; no es el puntaje de un modelo.",
      },
      {
        name: "Evaluar",
        records: "Respuestas guardadas, hora de envío según el servidor y resultados de los ítems objetivos.",
        decides: "Cómo leer el resultado, y si se extiende el tiempo, con un motivo que queda auditado.",
      },
      {
        name: "Entrevistar",
        records: "Scorecards independientes por atributo, con recomendación y nota obligatoria.",
        decides: "La recomendación de cada entrevistador, sin ver antes la de los demás.",
      },
      {
        name: "Decidir",
        records: "Cada cambio de etapa, con quién lo hizo y por qué.",
        decides: "Quién recibe una oferta.",
      },
      {
        name: "Contratar",
        records: "La oferta, la respuesta del candidato y las tareas de incorporación.",
        decides: "Los términos de la oferta y el plan del primer día.",
      },
    ],
  },

  careers: {
    title: "Tu vacante, con tu marca, dentro de tu sitio.",
    body:
      "Publica la vacante en tu página de empleo o insértala con un iframe. El formulario recibe nombre, correo, respuestas escritas y CV, y entrega un comprobante al candidato.",
    steps: ["Marca", "Vacante", "Postulación", "Comprobante"],
    brandTitle: "Adapta el formulario a tu marca",
    brandBody: "Tres colores, los mismos que controla el producto: fondo, texto y botón.",
    swatches: { background: "Fondo", text: "Texto", button: "Botón" },
    presets: "Combinaciones de ejemplo",
    form: {
      company: "Northstar Labs",
      role: "Analista de datos",
      meta: "Bogotá o remoto en Colombia",
      name: "Nombre completo",
      email: "Correo",
      essay: "¿Qué problema de datos resolviste el último año?",
      cv: "Adjuntar CV (PDF o DOCX)",
      submit: "Enviar postulación",
      receiptTitle: "Postulación recibida",
      receiptBody: "Guardamos tu postulación y te enviamos este comprobante. Puedes seguirla desde tu portal.",
      again: "Ver otra vez",
    },
    embedTitle: "Insértalo en tu sitio",
    embedBody: "Cada vacante publicada tiene su formulario para insertar.",
    knockoutTitle: "Criterios eliminatorios, definidos por ti",
    knockoutBody:
      "Una vacante puede exigir años mínimos de experiencia o autorización de trabajo. Si la respuesta no los cumple, la postulación se cierra y queda guardada, y tu equipo puede reabrirla. Es una regla que escribiste tú, no un modelo.",
    illustration: "Formulario de demostración con datos ficticios.",
  },

  pipeline: {
    title: "El pipeline muestra dónde está cada persona, y por qué.",
    body:
      "Cada vacante tiene sus etapas. Las tarjetas muestran la evidencia reunida: CV, evaluación, entrevistas. Cada movimiento queda registrado con quién lo hizo y por qué.",
    lanes: ["Postulación", "Revisión", "Evaluación", "Entrevista", "Oferta"],
    moveNote: "Movimiento hecho por una reclutadora",
    rule: "Una automatización puede abrir una revisión. No rechaza a nadie en silencio.",
    extras: [
      { name: "Notas y etiquetas", text: "Contexto compartido en cada postulación." },
      { name: "Exportación CSV", text: "Descarga el pipeline cuando lo necesites." },
      { name: "Importación CSV con simulación", text: "Revisa qué pasaría antes de importar." },
    ],
    planTitle: "Plan de contratación",
    planBody:
      "Define tus propias etapas, revisores, criterios de entrada y salida, la llave de la evaluación y el enfoque de cada scorecard. Cada transición guarda quién la hizo y por qué.",
    styleTitle: "Cuestionario de estilo de trabajo",
    styleBody:
      "Un cuestionario original de acuerdo o desacuerdo con cinco escalas: mente, información, decisiones, estructura e identidad. Es un dato informativo: no es un corte y no decide nada.",
    demoNote: "Tarjetas con datos de demostración.",
  },

  cv: {
    title: "Cada CV se vuelve evidencia que puedes buscar.",
    body:
      "Los CV en PDF, texto y DOCX se indexan en cargos, habilidades, educación, ubicaciones, años y líneas de experiencia. El archivo original se conserva.",
    fields: ["Habilidades", "Cargos", "Educación", "Ubicaciones", "Años", "Experiencia"],
    limits:
      "Los archivos .doc antiguos se guardan pero no se extraen. No se ejecutan macros. Las imágenes dentro del CV no se interpretan.",
    searchTitle: "Búsqueda booleana",
    searchBody:
      "Combina AND, OR, NOT, comillas y paréntesis. Las palabras sin operador deben aparecer todas.",
    searchLabel: "Consulta de búsqueda",
    presets: 'Prueba una consulta',
    results: "coincidencias",
    none: "Ningún CV de ejemplo coincide. Quita un término o usa OR.",
    screenTitle: "El filtro de CV cuenta, no califica",
    screenBody:
      "El filtro busca las palabras imprescindibles de la vacante y cuenta la evidencia encontrada. No es el puntaje de un modelo, y las imágenes no cuentan.",
    sample: "CV sintéticos de ejemplo",
  },

  assess: {
    title: "Evaluaciones que el reloj del navegador no puede alterar.",
    body:
      "Redacta una evaluación, define el tamaño del banco y publícala. Cada candidato recibe un subconjunto estable de preguntas y trabaja con guardado automático.",
    steps: [
      {
        name: "Banco",
        text: "Redacta, publica o archiva. Con un tamaño de banco, cada candidato recibe un subconjunto estable: si vuelve a entrar, ve las mismas preguntas.",
      },
      {
        name: "Intento",
        text: "Las respuestas se guardan solas. La fecha límite la marca la base de datos, no el navegador.",
      },
      {
        name: "Evidencia",
        text: "Al enviar, el candidato recibe un comprobante. Los ítems objetivos se califican solos; lo escrito espera a una persona.",
      },
      {
        name: "Revisión",
        text: "Si hace falta más tiempo, una persona del equipo lo extiende mientras el intento está abierto, con un motivo que queda en la auditoría.",
      },
    ],
    clockTitle: "Prueba a cambiar la hora",
    clockBrowser: "Reloj del navegador",
    clockServer: "Fecha límite del servidor",
    clockEdit: "Sumar 10 minutos al reloj local",
    clockReset: "Restablecer",
    clockNote: "Editar el temporizador en pantalla no agrega tiempo. La fecha límite vive en el servidor.",
    extendNote: "Extensión: solo con motivo, solo con el intento abierto, siempre auditada.",
    noKeys: "Las claves de respuesta nunca viajan al navegador del candidato.",
  },

  code: {
    title: "Evidencia de código para una revisión técnica, no un veredicto.",
    body:
      "Las preguntas de código se congelan por versión, y las que tienen casos ocultos se califican contra ellos. El resultado ordena la evidencia; la rúbrica la aplica una persona.",
    points: [
      { name: "Versiones congeladas", text: "El candidato responde la versión que se publicó, aunque luego la edites." },
      { name: "Casos ocultos", text: "Cuando una pregunta los tiene, los resultados esperados nunca viajan en la respuesta que recibe el navegador." },
      { name: "Calificación formal en JavaScript", text: "Corre aislada, con límite de tiempo y manejo de errores, en un servidor que permite aislar procesos. Hoy la calificación formal es solo para JavaScript." },
      { name: "Ejecuciones de muestra", text: "El editor ejecuta ejemplos en 12 lenguajes para que el candidato pruebe su idea. Una ejecución de muestra no es el puntaje." },
    ],
    rankTitle: "Cómo se ordenan las entregas",
    rank: ["Casos superados", "Clase de tiempo estimada", "Espacio", "Tiempo medido"],
    rankNote: "La clase de complejidad es una heurística. Una falla de infraestructura no se guarda como cero. La rúbrica humana sigue siendo necesaria.",
    sample: "Ejecución de muestra",
    score: "Calificación formal",
    hidden: "Caso oculto",
    passed: "superado",
    editorLabel: "Ejemplo de entrega de código (ilustración)",
  },

  interview: {
    title: "Entrevistas estructuradas: cada quien aporta su evidencia por separado.",
    body:
      "Agenda, sala en vivo, scorecard y decisión. Cada paso deja un registro y ninguna recomendación se convierte sola en un movimiento del pipeline.",
    tabs: [
      {
        name: "Agenda",
        text: "El candidato elige un horario abierto. Recibe un archivo ICS y un enlace para Google Calendar.",
      },
      {
        name: "Sala en vivo",
        text: "Código compartido por revisión, protección contra guardados obsoletos, chat y notas privadas del entrevistador. La videollamada ocurre en tu herramienta: RECRUIT4US guarda el enlace de la reunión.",
      },
      {
        name: "Scorecard",
        text: "Atributos que escribes en la vacante; cada entrevista se enfoca en algunos. Recomendación en cuatro niveles y una nota corta obligatoria. Al enviarse, se bloquea.",
      },
      {
        name: "Decisión",
        text: "El ranking de entrevistas ordena las recomendaciones ya enviadas. No anticipa nada y no mueve a nadie de etapa: la decisión la toma tu equipo.",
      },
    ],
    scale: ["Definitivamente no", "No", "Sí", "Definitivamente sí"],
    attributes: ["Comunicación", "Resolución de problemas", "SQL", "Colaboración"],
    focus: "Enfoque de esta entrevista",
    noteLabel: "Nota corta (obligatoria)",
    notePlaceholder: "Qué viste que respalda tu recomendación",
    submit: "Enviar scorecard",
    locked: "Scorecard enviada y bloqueada",
    hiddenOthers: "2 scorecards de otros entrevistadores",
    hiddenHint: "Se muestran cuando envías la tuya.",
    revealed: "Ahora puedes ver las demás",
    overall: "Recomendación general",
    needNote: "Escribe una nota corta para enviar.",
    needRating: "Elige una recomendación general.",
    reset: "Empezar de nuevo",
    roomCode: "Revisión",
    roomSaved: "Guardado",
    roomStale: "Otra persona guardó una revisión más nueva. Recarga antes de guardar.",
    privateNotes: "Notas privadas",
    meetingLink: "Enlace de la reunión",
    meetingHint: "Se abre en tu herramienta de video",
    ranking: "Ranking por recomendaciones enviadas",
    rankingNote: "Ilustración con datos ficticios. No mueve a nadie de etapa.",
    slider: {
      label: "Recorrido de una entrevista",
      roledesc: "carrusel",
      slide: "diapositiva",
      of: "de",
      prev: "Paso anterior",
      next: "Paso siguiente",
      goTo: "Ir a",
      hint: "Arrastra, usa las flechas del teclado o los botones.",
      step: "Paso",
    },
    demoNote: "Ilustración con datos ficticios, no es una captura del producto.",
    agenda: {
      view: "Vista del candidato",
      slots: ["09:00", "10:30", "12:00", "15:00", "16:30"],
      taken: "Tomado",
      free: "Libre",
      chosen: "Reservado",
      after: "Al reservar recibes un archivo ICS y un enlace para agregarla a tu calendario.",
      files: ["Archivo .ics", "Enlace de calendario"],
      more: "Ver la agenda completa",
    },
    room: {
      title: "Sala en vivo",
      file: "solucion.js",
      typing: "Valentina está escribiendo",
      newer: "El servidor tiene la revisión",
      yours: "Tu copia",
      save: "Guardar",
      reload: "Recargar",
      saved: "Guardado en la revisión",
      chat: "Chat",
      notesHint: "Solo tú ves estas notas.",
      notes: "Probó el caso vacío antes de que se lo pidiera. Preguntar por el costo en memoria.",
      messages: [
        { who: "Tú", text: "¿Por qué elegiste un Map?" },
        { who: "Valentina", text: "Para contar en una sola pasada y leer en tiempo constante." },
      ],
      chatLabel: "Escribe un mensaje",
      send: "Enviar",
      link: "video.northstar.example/sala-714",
      copy: "Copiar enlace",
      copied: "Enlace copiado",
      panels: "Paneles del entrevistador",
    },
    card: {
      candidate: "Valentina R.",
      kind: "Entrevista técnica",
      yours: "Tu scorecard",
      inFocus: "En foco",
      outFocus: "Lo cubre otra entrevista",
      rate: "Calificación de",
      noteMin: "Mínimo 8 caracteres.",
      lockedHint: "Una scorecard enviada ya no se edita.",
      hiddenLabel: "Oculta hasta que envíes la tuya",
      others: [
        { who: "Laura M.", kind: "Entrevista con el equipo", rec: 2, note: "Explica con claridad y pide contexto antes de proponer." },
        { who: "Andrés P.", kind: "Entrevista de SQL", rec: 3, note: "Resolvió la consulta con ventanas y probó los casos vacíos." },
      ],
      status: {
        sent: "Scorecard enviada. Se bloqueó y ahora ves las otras dos.",
        reset: "Scorecard reiniciada.",
      },
    },
    board: {
      rows: [
        { name: "Valentina R.", recs: [2, 3] },
        { name: "Mateo G.", recs: [2, 2, 3] },
        { name: "Camila T.", recs: [1, 2] },
      ],
      stage: "Etapa actual: Entrevista",
      average: "Promedio",
      outOf: "de 3",
      sent: "enviadas",
      yours: "Incluye tu scorecard",
      pending: "Tu scorecard aún no está enviada. El ranking solo usa las enviadas.",
      included: "Tu scorecard enviada ya cuenta en el ranking.",
      tie: "Empate",
      place: "Lugar",
      rulesTitle: "Cómo se ordena",
      rules: [
        "Promedio de las recomendaciones generales ya enviadas.",
        "Las calificaciones por atributo no entran en el promedio.",
        "Un empate comparte el mismo lugar.",
        "La etapa de cada persona no cambia: la mueve tu equipo.",
      ],
    },
  },

  schedule: {
    title: "Horarios que el candidato elige, sin choques.",
    body:
      "Publica horarios abiertos. El candidato elige uno y puede reprogramar. Si dos personas intentan tomar el mismo, solo una lo obtiene.",
    points: [
      "Horarios abiertos y autoagenda",
      "Protección contra choques",
      "Reprogramación",
      "Archivo ICS",
      "Enlace directo a Google Calendar",
    ],
    conditional:
      "La sincronización con un proveedor de calendario y la creación del enlace de reunión en el calendario de la empresa se activan cuando la empresa las configura.",
    week: ["Lun", "Mar", "Mié", "Jue", "Vie"],
    pick: "Elige un horario",
    taken: "Tomado por otro candidato",
    booked: "Reservado",
    collision: "Ese horario acaba de tomarse. Elige otro.",
    ics: "Descargar .ics",
    gcal: "Agregar a Google Calendar",
    demo: "Agenda de demostración.",
    timezone: "Hora de Bogotá",
    times: ["09:00", "10:30", "12:00", "14:30", "16:00"],
    daysLong: ["lunes", "martes", "miércoles", "jueves", "viernes"],
    free: "Libre",
    yours: "Tu horario",
    weekLabel: "Semana de demostración",
    dayPicker: "Día de la semana",
    eventTitle: "Entrevista de demostración, RECRUIT4US",
    eventDetails: "Evento de demostración creado desde el sitio de RECRUIT4US. No es una entrevista real.",
    eventLocation: "Enlace de la reunión de tu equipo",
    empty: "Aún no eliges un horario. Toca uno libre.",
    ticket: "Tu entrevista",
    reschedule: "Reprogramar",
    keep: "Mantener este horario",
    rescheduling: "Elige el nuevo horario. El actual se libera cuando confirmas otro.",
    simulate: "Simular otro candidato",
    otherSees: "Lo que ve el otro candidato",
    log: "Registro",
    logBooked: "Reservaste",
    logMoved: "Reprogramaste. Se liberó",
    logCollision: "Otro candidato intentó tomar tu horario y no lo obtuvo.",
    sequence: "El archivo .ics conserva su identificador y sube de versión cada vez que reprogramas.",
    to: "a",
    rangeTo: "al",
    current: "Actual",
    other: "Otro candidato",
    reset: "Empezar de nuevo",
    logEmpty: "Todavía no hay movimientos.",
  },

  sourcing: {
    title: "Talento que aún no ha postulado.",
    body:
      "Prospectos, pools, referidos y campañas viven aparte de las postulaciones. Una persona pasa a ser postulante solo cuando postula.",
    stepsLabel: "Del prospecto a la postulación",
    steps: [
      { name: "Prospecto", text: "Alguien que tu equipo quiere conocer. Todavía no es postulante." },
      { name: "Pool", text: "Agrupa prospectos para una necesidad futura." },
      { name: "Referido", text: "Una recomendación interna. Se sigue hasta la contratación." },
      { name: "Campaña", text: "Solo se inscribe quien dio su consentimiento. Una respuesta o un rebote detiene el envío." },
      { name: "Postulación", text: "Cuando la persona postula, entra al pipeline de la vacante." },
    ],
    sceneLabel:
      "Ilustración del sourcing, de izquierda a derecha: un campo de prospectos se agrupa en tres pools. De ahí salen dos caminos separados. Arriba, el referido interno, sin puerta. Abajo, la campaña: solo pasa quien dio su consentimiento; el resto sigue en su pool. En la campaña, una respuesta o un rebote detiene el envío. Al final, solo quien postula se convierte en una postulación y entra al pipeline.",
    pickStep: "Ver paso",
    consentTitle: "El consentimiento es la puerta",
    consentBody: "Las campañas solo llegan a personas que aceptaron ser contactadas, y tu equipo registra ese consentimiento. Una respuesta o un rebote detiene el envío.",
    boards: "Incluye un tablero de empleo de prueba. Los tableros externos se conectan cuando los configuras.",
  },

  offers: {
    title: "De la oferta al primer día.",
    body:
      "La oferta aparece en el portal del candidato. Cuando la acepta, se abren tareas de incorporación a partir de plantillas por cargo y ubicación.",
    offer: {
      label: "Oferta",
      role: "Analista de datos",
      company: "Northstar Labs",
      terms: [
        ["Inicio", "3 de noviembre"],
        ["Modalidad", "Híbrida, Bogotá"],
        ["Tipo de contrato", "Término indefinido"],
      ],
      accept: "Aceptar oferta",
      accepted: "Oferta aceptada",
    },
    tasksTitle: "Incorporación",
    tasks: ["Firmar contrato de trabajo", "Enviar documentos de afiliación", "Configurar equipo y accesos", "Primera reunión con el equipo"],
    notes: [
      "Cancelar una contratación conserva la oferta.",
      "La entrega a RR. HH. es una descarga, o un envío a tu HRIS cuando configuras su URL y token.",
    ],
    demo: "Oferta ficticia de demostración.",
    portal: "Portal del candidato",
    candidate: "Valentina R.",
    revision: "Versión 2, aprobada por tu equipo",
    message: "Nos alegra invitarte a Northstar Labs. Estos son los términos de la versión aprobada.",
    response: "Respuesta registrada para esta versión.",
    steps: ["Oferta en el portal", "Aceptada", "Tareas abiertas", "Primer día"],
    template: "Plantilla del cargo Analista de datos en Bogotá",
    owners: ["Tú", "Tú", "Equipo de TI", "Tu líder"],
    open: "Abierta",
    done: "Hecha",
    of: "de",
    doneCount: "hechas",
    hint: "Acepta la oferta o sigue bajando.",
    hintStatic: "Acepta la oferta para abrir la incorporación.",
    reset: "Ver otra vez",
    live: "Oferta aceptada. Se abrieron las tareas de incorporación.",
    progress: "Recorrido de la oferta",
  },

  portal: {
    tag: "Del lado del candidato",
    title: "El candidato ve su propio recorrido, y nada más.",
    body:
      "Con su correo y un código de un solo uso ve cómo avanzan sus postulaciones en esa empresa: evaluaciones, entrevistas, ofertas y mensajes, y puede responder. Con una cuenta de candidato, además ve sus tareas de incorporación y descarga sus datos.",
    tabsLabel: "Vista del portal del candidato",
    tabs: ["Entrar", "Mi recorrido", "Mis datos"],
    realTab: "Pantalla real",
    company: "Northstar Labs",
    portalName: "Portal del candidato",
    enter: {
      email: "Correo con el que postulaste",
      emailValue: "valentina.r@example.com",
      code: "Código de un solo uso",
      digits: "481027",
      note: "Llega por el correo saliente de la empresa, vence en 12 minutos y solo sirve para esta empresa.",
      unlock: "Ver mis postulaciones",
    },
    journey: {
      role: "Analista de datos",
      submitted: "Postulaste el 21 de septiembre",
      steps: ["Postulación", "Revisión", "Evaluación", "Entrevista", "Oferta"],
      current: 2,
      exercise: "Evaluación pendiente",
      exerciseHint: "El plazo lo marca el servidor, no el reloj del navegador.",
      exerciseTime: "25:00",
      message: "Mensaje de Northstar Labs",
      messageBody: "Gracias por tu postulación. Ya puedes presentar la evaluación técnica desde este portal.",
      reply: "Responder",
    },
    data: {
      title: "Descargar mis datos",
      account: "Con cuenta de candidato",
      body: "Desde su cuenta descarga un archivo JSON con cada postulación: la vacante, la empresa, el estado y la fecha.",
      button: "Descargar ejemplo (JSON)",
      file: "recruit4us-export-ejemplo.json",
      caption: "Ejemplo con datos ficticios. Misma estructura que la descarga real.",
    },
    seesTitle: "Lo que ve",
    sees: [
      "Sus postulaciones y la etapa de cada una",
      "Invitaciones a evaluaciones y sus entrevistas",
      "Su oferta y, con cuenta, sus tareas de incorporación",
      "Los mensajes de la empresa, y puede responder",
    ],
    hiddenTitle: "Lo que no ve",
    hidden: ["Notas internas del equipo", "Otros candidatos", "El espacio del reclutador"],
    verified:
      "Cada postulación se liga a un correo verificado: un correo sin verificar no puede reclamar la postulación de otra persona.",
    realAlt: "Portal del candidato real de RECRUIT4US, con sus postulaciones y el botón para descargar sus datos. Datos ficticios.",
  },

  trust: {
    title: "Los datos de cada empresa se quedan en su espacio.",
    body:
      "Las tablas del empleador usan seguridad por filas de PostgreSQL y cada solicitud valida que perteneces a la empresa. Cada puerta de entrada ve solo lo que le corresponde.",
    doors: [
      { name: "Página de empleo", text: "Solo ve vacantes publicadas." },
      { name: "Portal del candidato", text: "Cada persona ve sus propias postulaciones, ligadas a su sesión y a su correo verificado." },
      { name: "Espacio del reclutador", text: "Solo miembros de la empresa, validados en cada solicitud." },
    ],
    other: "Otra empresa",
    boundary: "Espacio de tu empresa",
    points: [
      { name: "Descarga de datos del candidato", text: "Desde su cuenta, cada candidato descarga sus postulaciones en JSON." },
      { name: "Retención", text: "La sección Privacidad de Configuración elimina los archivos de la empresa que superan la ventana de retención." },
      { name: "Auditoría", text: "Extensiones, cambios de etapa y decisiones sobre señales quedan registrados." },
    ],
    integrityTitle: "Señales de integridad: una persona revisa",
    integrityBody:
      "Los eventos de integridad y los puntajes de similitud son señales. No cambian la calificación ni rechazan postulaciones. Una persona confirma o descarta cada caso.",
    timeline: ["Inicio del intento", "Señal registrada", "Evidencia abierta", "Revisión humana"],
    signal: "Similitud alta con otra entrega",
    signalDetail: "Se muestra la evidencia para que una persona la lea. La calificación no cambia.",
    dismiss: "Descartar",
    confirm: "Confirmar",
    dismissed: "Caso descartado por una persona. La calificación no cambió.",
    confirmed: "Caso confirmado por una persona. La calificación no cambió; el equipo decide el siguiente paso.",
    reset: "Revisar otra vez",
    more: "Ver seguridad y privacidad",
    noCert:
      "No publicamos certificaciones que el producto no tiene. Esta sección describe controles que existen en el código.",
    sceneLabel:
      "Ilustración del aislamiento: el espacio de tu empresa es un volumen de vidrio con los datos de candidatos dentro. A su lado, separada por un límite, está otra empresa. Tres caminos entran por tres puertas: la página de empleo se detiene en las vacantes publicadas, el portal del candidato llega solo a los registros de esa persona y el espacio del reclutador entra a todo el espacio de la empresa. Ningún camino cruza hacia la otra empresa.",
    doorsTitle: "Tres puertas, cada una con su alcance",
    pointsTitle: "Lo que el candidato y tu equipo pueden hacer con los datos",
    published: "Vacantes publicadas",
    timelineLabel: "Recorrido de un caso de integridad",
    open: "Abrir la evidencia",
    pending: "Caso abierto. Falta la revisión de una persona.",
    opened: "Evidencia abierta. Una persona decide si descarta o confirma el caso.",
    scoreLabel: "Calificación",
    scoreValue: "82 de 100",
    unchanged: "Sin cambios",
    stepDone: "completado",
    stepCurrent: "paso actual",
    stepTodo: "pendiente",
    demo: "Caso ficticio de demostración.",
  },

  integrations: {
    title: "Integraciones: lo que viene incluido y lo que se activa al configurarlo.",
    body:
      "RECRUIT4US funciona completo dentro de su espacio. Los servicios externos se conectan cuando la empresa entrega sus credenciales; mientras tanto, el producto lo dice claramente.",
    groups: [
      {
        status: "included",
        name: "Incluido",
        items: [
          { name: "Bandeja de correo del espacio", text: "Los correos quedan capturados y visibles en la bandeja del espacio, en Configuración." },
          { name: "Archivo ICS y enlace a Google Calendar", text: "Para cada entrevista agendada." },
          { name: "Calificación formal de JavaScript", text: "Aislada y con límite de tiempo, en un servidor que permite aislar procesos." },
          { name: "Tablero de empleo de prueba", text: "Para ver cómo se distribuye una vacante." },
          { name: "Entrega a RR. HH. como descarga", text: "Sin configuración adicional." },
        ],
      },
      {
        status: "configurable",
        name: "Disponible al configurar",
        items: [
          { name: "Correo SMTP externo", text: "Estados de entrega: en cola, aceptado, entregado, diferido, rebotado, fallido y suprimido." },
          { name: "Eventos de entrega por webhook", text: "Entrega, rebote y queja llegan firmados." },
          { name: "Proveedor de calendario y enlace de reunión", text: "Con la cuenta de calendario conectada por la empresa." },
          { name: "Tableros de empleo externos", text: "Mediante el proveedor que configures." },
          { name: "Almacenamiento compatible con S3 o R2", text: "Sin configurarlo, los archivos se guardan en la base de datos." },
          { name: "HRIS por URL y token", text: "Envío de la entrega de incorporación." },
          { name: "Servicio de ejecuciones de muestra", text: "Judge0 público por defecto, o tu propia instancia. Solo para probar ejemplos." },
          { name: "Extracto analítico por HTTPS", text: "Hacia el destino que definas." },
        ],
      },
      {
        status: "not-connected",
        name: "No conectado hoy",
        items: [
          { name: "Envío de textos a celulares", text: "Las automatizaciones guardan el texto; no hay operador conectado para enviarlo." },
          { name: "Video de las entrevistas", text: "RECRUIT4US no aloja la llamada: las entrevistas usan el enlace de tu herramienta de video." },
        ],
      },
    ],
    automationTitle: "Automatizaciones con simulación y auditoría",
    automationBody:
      "Una regla puede guardar un correo, guardar un texto o enviar un dato. Antes de activarla, pruébala en simulación: el correo queda capturado y todo queda auditado. También puede anonimizar registros.",
    mailNote: "Una respuesta 250 del servidor SMTP significa aceptado, no entregado. La entrega se confirma con eventos del proveedor.",
    more: "Ver todas las integraciones",
    statusHint: {
      included: "Funciona dentro de RECRUIT4US, sin servicios externos.",
      configurable: "Se activa cuando la empresa entrega sus credenciales.",
      "not-connected": "El producto lo indica claramente y no simula el envío.",
    },
    automationSteps: [
      { name: "Simulación", text: "Ves qué haría la regla antes de activarla." },
      { name: "Correo capturado", text: "En simulación, el correo queda en la bandeja del espacio." },
      { name: "Auditoría", text: "Cada acción de la regla queda registrada." },
      { name: "Anonimización", text: "Una regla también puede anonimizar registros." },
    ],
    mailStates: ["En cola", "Aceptado", "Entregado"],
    mailGap: "Aceptado no es entregado",
  },

  tour: {
    title: "Pantallas reales del producto.",
    body: "Capturas del espacio de demostración Northstar Labs, con datos ficticios.",
    prev: "Pantalla anterior",
    next: "Pantalla siguiente",
    of: "de",
    drag: "Arrastra, usa las flechas o el teclado",
    label: "Recorrido por pantallas reales",
    slide: "Pantalla",
    loading: "Cargando capturas del producto",
    empty: "Las capturas del producto se están actualizando.",
    screens: [
      { name: "careers", caption: "Página de empleo pública con las vacantes publicadas." },
      { name: "embed", caption: "Formulario de una vacante insertado en el sitio de la empresa, con sus colores." },
      { name: "jobs", caption: "Vacantes del espacio, con su estado y sus postulaciones." },
      { name: "application", caption: "Una postulación con su CV original y el resultado del filtro explicado." },
      { name: "pipeline", caption: "Pipeline por vacante con etapas configurables e historial de movimientos." },
      { name: "assessment-attempt", caption: "Intento de evaluación con el tiempo controlado por el servidor." },
      { name: "code-attempt", caption: "Ejercicio de código con versión congelada y casos ocultos." },
      { name: "schedule", caption: "Horarios que el candidato reserva desde un enlace." },
      { name: "live-room", caption: "Sala de entrevista técnica con código compartido y notas privadas." },
      { name: "scorecard", caption: "Scorecard estructurado con atributos por vacante y una nota obligatoria." },
      { name: "sourcing", caption: "Sourcing con prospectos y referidos separados de quienes ya postularon." },
      { name: "offers", caption: "Oferta con aprobación de cada versión antes del envío." },
      { name: "onboarding", caption: "Incorporación con tareas según el cargo y la ubicación." },
      { name: "integrity", caption: "Caso de integridad abierto para que una persona lo revise." },
      { name: "privacy", caption: "Privacidad: retención de archivos y solicitudes de eliminación." },
      { name: "portal", caption: "Portal del candidato con sus postulaciones y la descarga en JSON." },
    ],
  },

  demo: {
    title: "Mira RECRUIT4US con tus propias vacantes.",
    body: "Cuéntanos cómo contrata tu equipo y preparamos una demostración con el recorrido que te interesa.",
    fields: {
      name: "Nombre",
      org: "Organización",
      email: "Correo de trabajo",
      phone: "Teléfono (opcional)",
      size: "Tamaño del equipo de reclutamiento",
      interest: "Qué te interesa ver",
      message: "Mensaje (opcional)",
    },
    sizes: ["1 a 3 personas", "4 a 10 personas", "11 a 30 personas", "Más de 30 personas"],
    interests: [
      "Vacantes y postulaciones",
      "Pipeline",
      "Evaluaciones",
      "Código",
      "Entrevistas",
      "Agenda",
      "Sourcing",
      "Ofertas e incorporación",
      "Privacidad y gobierno",
    ],
    submit: "Solicitar demo",
    sending: "Enviando…",
    sent: "Solicitud enviada. Te escribiremos al correo que dejaste.",
    mailto: "Abrimos tu correo con la solicitud lista para enviar.",
    error: "No pudimos enviar la solicitud. Escríbenos a",
    required: "Completa este campo.",
    invalidEmail: "Escribe un correo válido, como nombre@empresa.com.",
    privacy: "Solo usamos estos datos para responder tu solicitud. No pidas ni envíes datos de candidatos por aquí.",
    signIn: "¿Ya tienes una cuenta?",
    signInLink: "Ingresar",
    choose: "Elige una opción",
    interestHint: "Elige todas las que quieras.",
    review: "Revisa los campos marcados.",
    mailFallback: "Si tu correo no se abrió, escríbenos a",
    mailSubject: "Solicitud de demo de RECRUIT4US",
    mailIntro: "Hola, quiero una demostración de RECRUIT4US.",
    none: "Sin indicar",
    horizon: ["Invitar", "Postular", "Evaluar", "Incorporar"],
    horizonCaption: "La demostración termina donde termina el recorrido: una persona incorporada a tu equipo.",
    retry: "Intentar otra vez",
  },

  footer: {
    tagline: "El espacio de contratación de la familia 4US de TIGLOBAL.",
    product: "Producto",
    extra: [
      { id: "sourcing", label: "Sourcing" },
      { id: "portal", label: "Portal del candidato" },
    ],
    company: "TIGLOBAL",
    rights: "Todos los derechos reservados.",
    honest: "Las capturas usan datos ficticios. Las integraciones externas se activan al configurarlas.",
  },

  pages: {
    security: {
      title: "Seguridad y privacidad",
      lede: "Cómo RECRUIT4US separa los datos de cada empresa, protege al candidato y deja registro de las decisiones.",
      indexLabel: "En esta página",
      detailTitle: "Cada control, en detalle",
      sections: [
        {
          id: "aislamiento",
          title: "Aislamiento entre empresas",
          body: "Las empresas comparten la misma base de datos. Lo que las separa es la seguridad por filas de PostgreSQL en las tablas del empleador y la validación de membresía en cada solicitud: una consulta de tu equipo solo devuelve filas de tu empresa.",
          points: [
            "Seguridad por filas en las tablas del empleador.",
            "Cada solicitud valida que la persona pertenece a la empresa.",
            "El salario de una oferta solo lo ven los roles autorizados.",
          ],
        },
        {
          id: "candidato",
          title: "El camino del candidato",
          body: "El candidato no entra al espacio del reclutador. Su portal muestra sus propias postulaciones, evaluaciones, entrevistas y ofertas, ligadas a su sesión y a su correo verificado.",
          points: [
            "Sin cuenta, abre su postulación con un código que se envía a su correo. El código llega a bandejas reales cuando el correo SMTP está configurado.",
            "Las claves de respuesta de las evaluaciones se quedan en el servidor.",
          ],
        },
        {
          id: "descarga",
          title: "Descarga de datos del candidato",
          body: "Desde su portal, cada candidato con cuenta descarga sus postulaciones en un archivo JSON con la vacante, la empresa, el estado y la fecha.",
          points: [],
        },
        {
          id: "retencion",
          title: "Retención y eliminación",
          body: "En la sección Privacidad de Configuración defines cuánto tiempo conservas los archivos, y una persona de tu equipo elimina los que superan esa ventana. Las solicitudes de eliminación anonimizan los datos de contacto y los archivos del candidato dentro de tu empresa.",
          points: ["La limpieza por retención es una acción manual, con una ventana mínima de 30 días.", "La limpieza no borra las copias de respaldo."],
        },
        {
          id: "auditoria",
          title: "Auditoría",
          body: "Las acciones importantes del equipo quedan en el registro de auditoría: extensiones de tiempo con su motivo, cambios de etapa, decisiones sobre señales y acciones de las automatizaciones.",
          points: [],
        },
        {
          id: "integridad",
          title: "Señales de integridad",
          body: "Los eventos de integridad de un intento y la similitud entre entregas abren un caso con su evidencia. Una persona lo descarta o lo confirma. La calificación no cambia y nadie queda rechazado por una señal.",
          points: [],
        },
      ],
      dontTitle: "Lo que no afirmamos",
      donts: [
        "No publicamos certificaciones que el producto no tiene.",
        "Las empresas no tienen instalaciones separadas: la separación se hace por filas y por membresía.",
        "Una señal de integridad no es una prueba. Una persona revisa la evidencia.",
        "La anonimización atiende solicitudes dentro de tu empresa; no es una garantía legal.",
      ],
      ctaTitle: "Revisa estos controles con tu equipo.",
      ctaBody: "En la demostración mostramos cada control dentro del producto, con datos ficticios.",
    },
    integrations: {
      title: "Integraciones",
      lede: "Qué viene incluido, qué se activa al configurarlo y qué no está conectado hoy.",
      notesTitle: "Notas técnicas",
      notesBody: "Los detalles que conviene conocer antes de conectar un servicio.",
      mail: {
        title: "Estados del correo",
        body: "Sin SMTP configurado, los correos quedan capturados en la bandeja del espacio y nada sale de él. Con SMTP, cada correo muestra su estado.",
        states: [
          { name: "En cola", text: "Guardado y esperando su turno de envío." },
          { name: "Aceptado", text: "El servidor SMTP respondió 250. Todavía no es entregado." },
          { name: "Entregado", text: "El proveedor confirmó la entrega con un evento firmado." },
          { name: "Diferido", text: "El servidor pidió reintentar más tarde." },
          { name: "Rebotado", text: "El servidor de destino devolvió el mensaje." },
          { name: "Fallido", text: "El envío no se completó." },
          { name: "Suprimido", text: "La dirección está en la lista de supresión y no se intenta el envío." },
        ],
      },
      files: {
        title: "Archivos",
        body: "Sin almacenamiento configurado, los archivos se guardan en la base de datos y se descargan con una autorización de corta duración. Al configurar un almacenamiento compatible con S3 o R2, los archivos nuevos van ahí y los anteriores siguen disponibles.",
      },
      hr: {
        title: "Entrega a RR. HH.",
        body: "La entrega de incorporación es un archivo JSON que descargas. Al configurar la URL y el token de tu HRIS, se envía una sola vez por postulación, y el salario se omite para los roles sin permiso de compensación.",
      },
      code: {
        title: "Ejecuciones de muestra y calificación formal",
        body: "El editor admite 12 lenguajes para ejecuciones de muestra. Una ejecución de muestra sirve para practicar y no es una calificación. La calificación formal se ejecuta solo en JavaScript, en un proceso aislado del servidor. Sin configuración, las ejecuciones de muestra usan un servicio público; puedes apuntar a tu propia instancia.",
      },
      ctaTitle: "Mira cada integración en el producto.",
      ctaBody: "En la demostración ves qué funciona incluido y qué pasa cuando conectas un servicio.",
    },
    contact: {
      title: "Solicitar demo",
      lede: "Una demostración con tus vacantes, tu equipo y el recorrido que quieres ver.",
      nextTitle: "Qué pasa después",
      next: [
        "Te respondemos al correo de trabajo que dejaste.",
        "Acordamos el recorrido y el momento de la demostración.",
        "Te mostramos el producto con datos ficticios del espacio de demostración.",
      ],
    },
    notFound: {
      title: "Esta página no está en el recorrido.",
      body: "La dirección no existe o cambió. Vuelve al inicio para seguir.",
      cta: "Volver al inicio",
    },
  },
};

export type Copy = typeof es;
