/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCompanySlugRouteRouteImport } from './routes/app/$companySlug/route'
import { Route as BookTokenRouteImport } from './routes/book/$token'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as CodeTokenRouteImport } from './routes/code/$token'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as LiveTokenRouteImport } from './routes/live/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiMailEventsRouteImport } from './routes/api/mail/events'
import { Route as ApiProviderCallbackRouteImport } from './routes/api/provider/callback'
import { Route as AppCompanySlugIndexRouteImport } from './routes/app/$companySlug/index'
import { Route as AppCompanySlugAssessmentsRouteImport } from './routes/app/$companySlug/assessments'
import { Route as AppCompanySlugAutomationsRouteImport } from './routes/app/$companySlug/automations'
import { Route as AppCompanySlugCalendarRouteImport } from './routes/app/$companySlug/calendar'
import { Route as AppCompanySlugCandidatesRouteImport } from './routes/app/$companySlug/candidates'
import { Route as AppCompanySlugConnectorsRouteImport } from './routes/app/$companySlug/connectors'
import { Route as AppCompanySlugCrmRouteImport } from './routes/app/$companySlug/crm'
import { Route as AppCompanySlugInboxRouteImport } from './routes/app/$companySlug/inbox'
import { Route as AppCompanySlugIntegrityRouteImport } from './routes/app/$companySlug/integrity'
import { Route as AppCompanySlugInterviewsRouteImport } from './routes/app/$companySlug/interviews'
import { Route as AppCompanySlugMailRouteImport } from './routes/app/$companySlug/mail'
import { Route as AppCompanySlugOffersRouteImport } from './routes/app/$companySlug/offers'
import { Route as AppCompanySlugOnboardingRouteImport } from './routes/app/$companySlug/onboarding'
import { Route as AppCompanySlugPlansRouteImport } from './routes/app/$companySlug/plans'
import { Route as AppCompanySlugQuestionsRouteImport } from './routes/app/$companySlug/questions'
import { Route as AppCompanySlugReportsRouteImport } from './routes/app/$companySlug/reports'
import { Route as AppCompanySlugReviewsRouteImport } from './routes/app/$companySlug/reviews'
import { Route as AppCompanySlugSandboxesRouteImport } from './routes/app/$companySlug/sandboxes'
import { Route as AppCompanySlugSettingsRouteImport } from './routes/app/$companySlug/settings'
import { Route as CandidateApplicationsApplicationIdRouteImport } from './routes/candidate/applications/$applicationId'
import { Route as CandidateAttemptsAttemptIdRouteImport } from './routes/candidate/attempts/$attemptId'
import { Route as CandidateOffersOfferIdRouteImport } from './routes/candidate/offers/$offerId'
import { Route as CareersCompanySlugIndexRouteImport } from './routes/careers/$companySlug/index'
import { Route as CareersCompanySlugJobSlugRouteImport } from './routes/careers/$companySlug/$jobSlug'
import { Route as EmbedCompanySlugJobSlugRouteImport } from './routes/embed/$companySlug/$jobSlug'
import { Route as AppCompanySlugApplicationsApplicationIdRouteImport } from './routes/app/$companySlug/applications/$applicationId'
import { Route as AppCompanySlugJobsIndexRouteImport } from './routes/app/$companySlug/jobs/index'
import { Route as AppCompanySlugJobsJobIdRouteImport } from './routes/app/$companySlug/jobs/$jobId'
import { Route as AppCompanySlugJobsJobIdPipelineRouteImport } from './routes/app/$companySlug/jobs/$jobId/pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugRouteRoute = AppCompanySlugRouteRouteImport.update({
  id: '/app/$companySlug',
  path: '/app/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeTokenRoute = CodeTokenRouteImport.update({
  id: '/code/$token',
  path: '/code/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTokenRoute = LiveTokenRouteImport.update({
  id: '/live/$token',
  path: '/live/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailEventsRoute = ApiMailEventsRouteImport.update({
  id: '/api/mail/events',
  path: '/api/mail/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderCallbackRoute = ApiProviderCallbackRouteImport.update({
  id: '/api/provider/callback',
  path: '/api/provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugIndexRoute = AppCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugAssessmentsRoute =
  AppCompanySlugAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugAutomationsRoute =
  AppCompanySlugAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugCalendarRoute = AppCompanySlugCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugCandidatesRoute =
  AppCompanySlugCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugConnectorsRoute =
  AppCompanySlugConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugCrmRoute = AppCompanySlugCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugInboxRoute = AppCompanySlugInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugIntegrityRoute = AppCompanySlugIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugInterviewsRoute =
  AppCompanySlugInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugMailRoute = AppCompanySlugMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugOffersRoute = AppCompanySlugOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugOnboardingRoute =
  AppCompanySlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugPlansRoute = AppCompanySlugPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugQuestionsRoute = AppCompanySlugQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugReportsRoute = AppCompanySlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugReviewsRoute = AppCompanySlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugSandboxesRoute = AppCompanySlugSandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugSettingsRoute = AppCompanySlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const CandidateApplicationsApplicationIdRoute =
  CandidateApplicationsApplicationIdRouteImport.update({
    id: '/candidate/applications/$applicationId',
    path: '/candidate/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateAttemptsAttemptIdRoute =
  CandidateAttemptsAttemptIdRouteImport.update({
    id: '/candidate/attempts/$attemptId',
    path: '/candidate/attempts/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateOffersOfferIdRoute = CandidateOffersOfferIdRouteImport.update({
  id: '/candidate/offers/$offerId',
  path: '/candidate/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCompanySlugIndexRoute = CareersCompanySlugIndexRouteImport.update({
  id: '/careers/$companySlug/',
  path: '/careers/$companySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCompanySlugJobSlugRoute =
  CareersCompanySlugJobSlugRouteImport.update({
    id: '/careers/$companySlug/$jobSlug',
    path: '/careers/$companySlug/$jobSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmbedCompanySlugJobSlugRoute = EmbedCompanySlugJobSlugRouteImport.update({
  id: '/embed/$companySlug/$jobSlug',
  path: '/embed/$companySlug/$jobSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugApplicationsApplicationIdRoute =
  AppCompanySlugApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugJobsIndexRoute = AppCompanySlugJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugJobsJobIdRoute = AppCompanySlugJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugJobsJobIdPipelineRoute =
  AppCompanySlugJobsJobIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AppCompanySlugJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notice': typeof NoticeRoute
  '/status': typeof StatusRoute
  '/app/$companySlug': typeof AppCompanySlugRouteRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/code/$token': typeof CodeTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/app/': typeof AppIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/mail/events': typeof ApiMailEventsRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/calendar': typeof AppCompanySlugCalendarRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/connectors': typeof AppCompanySlugConnectorsRoute
  '/app/$companySlug/crm': typeof AppCompanySlugCrmRoute
  '/app/$companySlug/inbox': typeof AppCompanySlugInboxRoute
  '/app/$companySlug/integrity': typeof AppCompanySlugIntegrityRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/mail': typeof AppCompanySlugMailRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/onboarding': typeof AppCompanySlugOnboardingRoute
  '/app/$companySlug/plans': typeof AppCompanySlugPlansRoute
  '/app/$companySlug/questions': typeof AppCompanySlugQuestionsRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/sandboxes': typeof AppCompanySlugSandboxesRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/embed/$companySlug/$jobSlug': typeof EmbedCompanySlugJobSlugRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug/': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs/': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notice': typeof NoticeRoute
  '/status': typeof StatusRoute
  '/book/$token': typeof BookTokenRoute
  '/code/$token': typeof CodeTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/app': typeof AppIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/mail/events': typeof ApiMailEventsRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/calendar': typeof AppCompanySlugCalendarRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/connectors': typeof AppCompanySlugConnectorsRoute
  '/app/$companySlug/crm': typeof AppCompanySlugCrmRoute
  '/app/$companySlug/inbox': typeof AppCompanySlugInboxRoute
  '/app/$companySlug/integrity': typeof AppCompanySlugIntegrityRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/mail': typeof AppCompanySlugMailRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/onboarding': typeof AppCompanySlugOnboardingRoute
  '/app/$companySlug/plans': typeof AppCompanySlugPlansRoute
  '/app/$companySlug/questions': typeof AppCompanySlugQuestionsRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/sandboxes': typeof AppCompanySlugSandboxesRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/embed/$companySlug/$jobSlug': typeof EmbedCompanySlugJobSlugRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/app/$companySlug': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notice': typeof NoticeRoute
  '/status': typeof StatusRoute
  '/app/$companySlug': typeof AppCompanySlugRouteRouteWithChildren
  '/book/$token': typeof BookTokenRoute
  '/code/$token': typeof CodeTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/app/': typeof AppIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/mail/events': typeof ApiMailEventsRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/calendar': typeof AppCompanySlugCalendarRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/connectors': typeof AppCompanySlugConnectorsRoute
  '/app/$companySlug/crm': typeof AppCompanySlugCrmRoute
  '/app/$companySlug/inbox': typeof AppCompanySlugInboxRoute
  '/app/$companySlug/integrity': typeof AppCompanySlugIntegrityRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/mail': typeof AppCompanySlugMailRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/onboarding': typeof AppCompanySlugOnboardingRoute
  '/app/$companySlug/plans': typeof AppCompanySlugPlansRoute
  '/app/$companySlug/questions': typeof AppCompanySlugQuestionsRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/sandboxes': typeof AppCompanySlugSandboxesRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/embed/$companySlug/$jobSlug': typeof EmbedCompanySlugJobSlugRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug/': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs/': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notice'
    | '/status'
    | '/app/$companySlug'
    | '/book/$token'
    | '/code/$token'
    | '/invite/$token'
    | '/live/$token'
    | '/app/'
    | '/candidate/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/mail/events'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/calendar'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/connectors'
    | '/app/$companySlug/crm'
    | '/app/$companySlug/inbox'
    | '/app/$companySlug/integrity'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/mail'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/onboarding'
    | '/app/$companySlug/plans'
    | '/app/$companySlug/questions'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/sandboxes'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/embed/$companySlug/$jobSlug'
    | '/api/health/'
    | '/app/$companySlug/'
    | '/careers/$companySlug/'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs/'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notice'
    | '/status'
    | '/book/$token'
    | '/code/$token'
    | '/invite/$token'
    | '/live/$token'
    | '/app'
    | '/candidate'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/mail/events'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/calendar'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/connectors'
    | '/app/$companySlug/crm'
    | '/app/$companySlug/inbox'
    | '/app/$companySlug/integrity'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/mail'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/onboarding'
    | '/app/$companySlug/plans'
    | '/app/$companySlug/questions'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/sandboxes'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/embed/$companySlug/$jobSlug'
    | '/api/health'
    | '/app/$companySlug'
    | '/careers/$companySlug'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notice'
    | '/status'
    | '/app/$companySlug'
    | '/book/$token'
    | '/code/$token'
    | '/invite/$token'
    | '/live/$token'
    | '/app/'
    | '/candidate/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/mail/events'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/calendar'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/connectors'
    | '/app/$companySlug/crm'
    | '/app/$companySlug/inbox'
    | '/app/$companySlug/integrity'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/mail'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/onboarding'
    | '/app/$companySlug/plans'
    | '/app/$companySlug/questions'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/sandboxes'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/embed/$companySlug/$jobSlug'
    | '/api/health/'
    | '/app/$companySlug/'
    | '/careers/$companySlug/'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs/'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NoticeRoute: typeof NoticeRoute
  StatusRoute: typeof StatusRoute
  AppCompanySlugRouteRoute: typeof AppCompanySlugRouteRouteWithChildren
  BookTokenRoute: typeof BookTokenRoute
  CodeTokenRoute: typeof CodeTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LiveTokenRoute: typeof LiveTokenRoute
  AppIndexRoute: typeof AppIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiMailEventsRoute: typeof ApiMailEventsRoute
  ApiProviderCallbackRoute: typeof ApiProviderCallbackRoute
  CandidateApplicationsApplicationIdRoute: typeof CandidateApplicationsApplicationIdRoute
  CandidateAttemptsAttemptIdRoute: typeof CandidateAttemptsAttemptIdRoute
  CandidateOffersOfferIdRoute: typeof CandidateOffersOfferIdRoute
  CareersCompanySlugJobSlugRoute: typeof CareersCompanySlugJobSlugRoute
  EmbedCompanySlugJobSlugRoute: typeof EmbedCompanySlugJobSlugRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  CareersCompanySlugIndexRoute: typeof CareersCompanySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug': {
      id: '/app/$companySlug'
      path: '/app/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/$token': {
      id: '/code/$token'
      path: '/code/$token'
      fullPath: '/code/$token'
      preLoaderRoute: typeof CodeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$token': {
      id: '/live/$token'
      path: '/live/$token'
      fullPath: '/live/$token'
      preLoaderRoute: typeof LiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/events': {
      id: '/api/mail/events'
      path: '/api/mail/events'
      fullPath: '/api/mail/events'
      preLoaderRoute: typeof ApiMailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider/callback': {
      id: '/api/provider/callback'
      path: '/api/provider/callback'
      fullPath: '/api/provider/callback'
      preLoaderRoute: typeof ApiProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/': {
      id: '/app/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/assessments': {
      id: '/app/$companySlug/assessments'
      path: '/assessments'
      fullPath: '/app/$companySlug/assessments'
      preLoaderRoute: typeof AppCompanySlugAssessmentsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/automations': {
      id: '/app/$companySlug/automations'
      path: '/automations'
      fullPath: '/app/$companySlug/automations'
      preLoaderRoute: typeof AppCompanySlugAutomationsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/calendar': {
      id: '/app/$companySlug/calendar'
      path: '/calendar'
      fullPath: '/app/$companySlug/calendar'
      preLoaderRoute: typeof AppCompanySlugCalendarRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/candidates': {
      id: '/app/$companySlug/candidates'
      path: '/candidates'
      fullPath: '/app/$companySlug/candidates'
      preLoaderRoute: typeof AppCompanySlugCandidatesRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/connectors': {
      id: '/app/$companySlug/connectors'
      path: '/connectors'
      fullPath: '/app/$companySlug/connectors'
      preLoaderRoute: typeof AppCompanySlugConnectorsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/crm': {
      id: '/app/$companySlug/crm'
      path: '/crm'
      fullPath: '/app/$companySlug/crm'
      preLoaderRoute: typeof AppCompanySlugCrmRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/inbox': {
      id: '/app/$companySlug/inbox'
      path: '/inbox'
      fullPath: '/app/$companySlug/inbox'
      preLoaderRoute: typeof AppCompanySlugInboxRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/integrity': {
      id: '/app/$companySlug/integrity'
      path: '/integrity'
      fullPath: '/app/$companySlug/integrity'
      preLoaderRoute: typeof AppCompanySlugIntegrityRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/interviews': {
      id: '/app/$companySlug/interviews'
      path: '/interviews'
      fullPath: '/app/$companySlug/interviews'
      preLoaderRoute: typeof AppCompanySlugInterviewsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/mail': {
      id: '/app/$companySlug/mail'
      path: '/mail'
      fullPath: '/app/$companySlug/mail'
      preLoaderRoute: typeof AppCompanySlugMailRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/offers': {
      id: '/app/$companySlug/offers'
      path: '/offers'
      fullPath: '/app/$companySlug/offers'
      preLoaderRoute: typeof AppCompanySlugOffersRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/onboarding': {
      id: '/app/$companySlug/onboarding'
      path: '/onboarding'
      fullPath: '/app/$companySlug/onboarding'
      preLoaderRoute: typeof AppCompanySlugOnboardingRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/plans': {
      id: '/app/$companySlug/plans'
      path: '/plans'
      fullPath: '/app/$companySlug/plans'
      preLoaderRoute: typeof AppCompanySlugPlansRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/questions': {
      id: '/app/$companySlug/questions'
      path: '/questions'
      fullPath: '/app/$companySlug/questions'
      preLoaderRoute: typeof AppCompanySlugQuestionsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/reports': {
      id: '/app/$companySlug/reports'
      path: '/reports'
      fullPath: '/app/$companySlug/reports'
      preLoaderRoute: typeof AppCompanySlugReportsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/reviews': {
      id: '/app/$companySlug/reviews'
      path: '/reviews'
      fullPath: '/app/$companySlug/reviews'
      preLoaderRoute: typeof AppCompanySlugReviewsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/sandboxes': {
      id: '/app/$companySlug/sandboxes'
      path: '/sandboxes'
      fullPath: '/app/$companySlug/sandboxes'
      preLoaderRoute: typeof AppCompanySlugSandboxesRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/settings': {
      id: '/app/$companySlug/settings'
      path: '/settings'
      fullPath: '/app/$companySlug/settings'
      preLoaderRoute: typeof AppCompanySlugSettingsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/candidate/applications/$applicationId': {
      id: '/candidate/applications/$applicationId'
      path: '/candidate/applications/$applicationId'
      fullPath: '/candidate/applications/$applicationId'
      preLoaderRoute: typeof CandidateApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/attempts/$attemptId': {
      id: '/candidate/attempts/$attemptId'
      path: '/candidate/attempts/$attemptId'
      fullPath: '/candidate/attempts/$attemptId'
      preLoaderRoute: typeof CandidateAttemptsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/offers/$offerId': {
      id: '/candidate/offers/$offerId'
      path: '/candidate/offers/$offerId'
      fullPath: '/candidate/offers/$offerId'
      preLoaderRoute: typeof CandidateOffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$companySlug/': {
      id: '/careers/$companySlug/'
      path: '/careers/$companySlug'
      fullPath: '/careers/$companySlug/'
      preLoaderRoute: typeof CareersCompanySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$companySlug/$jobSlug': {
      id: '/careers/$companySlug/$jobSlug'
      path: '/careers/$companySlug/$jobSlug'
      fullPath: '/careers/$companySlug/$jobSlug'
      preLoaderRoute: typeof CareersCompanySlugJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$companySlug/$jobSlug': {
      id: '/embed/$companySlug/$jobSlug'
      path: '/embed/$companySlug/$jobSlug'
      fullPath: '/embed/$companySlug/$jobSlug'
      preLoaderRoute: typeof EmbedCompanySlugJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/applications/$applicationId': {
      id: '/app/$companySlug/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/app/$companySlug/applications/$applicationId'
      preLoaderRoute: typeof AppCompanySlugApplicationsApplicationIdRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/': {
      id: '/app/$companySlug/jobs/'
      path: '/jobs'
      fullPath: '/app/$companySlug/jobs/'
      preLoaderRoute: typeof AppCompanySlugJobsIndexRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/$jobId': {
      id: '/app/$companySlug/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/$companySlug/jobs/$jobId'
      preLoaderRoute: typeof AppCompanySlugJobsJobIdRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/$jobId/pipeline': {
      id: '/app/$companySlug/jobs/$jobId/pipeline'
      path: '/pipeline'
      fullPath: '/app/$companySlug/jobs/$jobId/pipeline'
      preLoaderRoute: typeof AppCompanySlugJobsJobIdPipelineRouteImport
      parentRoute: typeof AppCompanySlugJobsJobIdRoute
    }
  }
}

interface AppCompanySlugJobsJobIdRouteChildren {
  AppCompanySlugJobsJobIdPipelineRoute: typeof AppCompanySlugJobsJobIdPipelineRoute
}

const AppCompanySlugJobsJobIdRouteChildren: AppCompanySlugJobsJobIdRouteChildren =
  {
    AppCompanySlugJobsJobIdPipelineRoute: AppCompanySlugJobsJobIdPipelineRoute,
  }

const AppCompanySlugJobsJobIdRouteWithChildren =
  AppCompanySlugJobsJobIdRoute._addFileChildren(
    AppCompanySlugJobsJobIdRouteChildren,
  )

interface AppCompanySlugRouteRouteChildren {
  AppCompanySlugAssessmentsRoute: typeof AppCompanySlugAssessmentsRoute
  AppCompanySlugAutomationsRoute: typeof AppCompanySlugAutomationsRoute
  AppCompanySlugCalendarRoute: typeof AppCompanySlugCalendarRoute
  AppCompanySlugCandidatesRoute: typeof AppCompanySlugCandidatesRoute
  AppCompanySlugConnectorsRoute: typeof AppCompanySlugConnectorsRoute
  AppCompanySlugCrmRoute: typeof AppCompanySlugCrmRoute
  AppCompanySlugInboxRoute: typeof AppCompanySlugInboxRoute
  AppCompanySlugIntegrityRoute: typeof AppCompanySlugIntegrityRoute
  AppCompanySlugInterviewsRoute: typeof AppCompanySlugInterviewsRoute
  AppCompanySlugMailRoute: typeof AppCompanySlugMailRoute
  AppCompanySlugOffersRoute: typeof AppCompanySlugOffersRoute
  AppCompanySlugOnboardingRoute: typeof AppCompanySlugOnboardingRoute
  AppCompanySlugPlansRoute: typeof AppCompanySlugPlansRoute
  AppCompanySlugQuestionsRoute: typeof AppCompanySlugQuestionsRoute
  AppCompanySlugReportsRoute: typeof AppCompanySlugReportsRoute
  AppCompanySlugReviewsRoute: typeof AppCompanySlugReviewsRoute
  AppCompanySlugSandboxesRoute: typeof AppCompanySlugSandboxesRoute
  AppCompanySlugSettingsRoute: typeof AppCompanySlugSettingsRoute
  AppCompanySlugIndexRoute: typeof AppCompanySlugIndexRoute
  AppCompanySlugApplicationsApplicationIdRoute: typeof AppCompanySlugApplicationsApplicationIdRoute
  AppCompanySlugJobsJobIdRoute: typeof AppCompanySlugJobsJobIdRouteWithChildren
  AppCompanySlugJobsIndexRoute: typeof AppCompanySlugJobsIndexRoute
}

const AppCompanySlugRouteRouteChildren: AppCompanySlugRouteRouteChildren = {
  AppCompanySlugAssessmentsRoute: AppCompanySlugAssessmentsRoute,
  AppCompanySlugAutomationsRoute: AppCompanySlugAutomationsRoute,
  AppCompanySlugCalendarRoute: AppCompanySlugCalendarRoute,
  AppCompanySlugCandidatesRoute: AppCompanySlugCandidatesRoute,
  AppCompanySlugConnectorsRoute: AppCompanySlugConnectorsRoute,
  AppCompanySlugCrmRoute: AppCompanySlugCrmRoute,
  AppCompanySlugInboxRoute: AppCompanySlugInboxRoute,
  AppCompanySlugIntegrityRoute: AppCompanySlugIntegrityRoute,
  AppCompanySlugInterviewsRoute: AppCompanySlugInterviewsRoute,
  AppCompanySlugMailRoute: AppCompanySlugMailRoute,
  AppCompanySlugOffersRoute: AppCompanySlugOffersRoute,
  AppCompanySlugOnboardingRoute: AppCompanySlugOnboardingRoute,
  AppCompanySlugPlansRoute: AppCompanySlugPlansRoute,
  AppCompanySlugQuestionsRoute: AppCompanySlugQuestionsRoute,
  AppCompanySlugReportsRoute: AppCompanySlugReportsRoute,
  AppCompanySlugReviewsRoute: AppCompanySlugReviewsRoute,
  AppCompanySlugSandboxesRoute: AppCompanySlugSandboxesRoute,
  AppCompanySlugSettingsRoute: AppCompanySlugSettingsRoute,
  AppCompanySlugIndexRoute: AppCompanySlugIndexRoute,
  AppCompanySlugApplicationsApplicationIdRoute:
    AppCompanySlugApplicationsApplicationIdRoute,
  AppCompanySlugJobsJobIdRoute: AppCompanySlugJobsJobIdRouteWithChildren,
  AppCompanySlugJobsIndexRoute: AppCompanySlugJobsIndexRoute,
}

const AppCompanySlugRouteRouteWithChildren =
  AppCompanySlugRouteRoute._addFileChildren(AppCompanySlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NoticeRoute: NoticeRoute,
  StatusRoute: StatusRoute,
  AppCompanySlugRouteRoute: AppCompanySlugRouteRouteWithChildren,
  BookTokenRoute: BookTokenRoute,
  CodeTokenRoute: CodeTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  LiveTokenRoute: LiveTokenRoute,
  AppIndexRoute: AppIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiMailEventsRoute: ApiMailEventsRoute,
  ApiProviderCallbackRoute: ApiProviderCallbackRoute,
  CandidateApplicationsApplicationIdRoute:
    CandidateApplicationsApplicationIdRoute,
  CandidateAttemptsAttemptIdRoute: CandidateAttemptsAttemptIdRoute,
  CandidateOffersOfferIdRoute: CandidateOffersOfferIdRoute,
  CareersCompanySlugJobSlugRoute: CareersCompanySlugJobSlugRoute,
  EmbedCompanySlugJobSlugRoute: EmbedCompanySlugJobSlugRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  CareersCompanySlugIndexRoute: CareersCompanySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
