/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCompanySlugRouteRouteImport } from './routes/app/$companySlug/route'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiProviderCallbackRouteImport } from './routes/api/provider/callback'
import { Route as AppCompanySlugIndexRouteImport } from './routes/app/$companySlug/index'
import { Route as AppCompanySlugAssessmentsRouteImport } from './routes/app/$companySlug/assessments'
import { Route as AppCompanySlugAutomationsRouteImport } from './routes/app/$companySlug/automations'
import { Route as AppCompanySlugCandidatesRouteImport } from './routes/app/$companySlug/candidates'
import { Route as AppCompanySlugInterviewsRouteImport } from './routes/app/$companySlug/interviews'
import { Route as AppCompanySlugOffersRouteImport } from './routes/app/$companySlug/offers'
import { Route as AppCompanySlugReportsRouteImport } from './routes/app/$companySlug/reports'
import { Route as AppCompanySlugReviewsRouteImport } from './routes/app/$companySlug/reviews'
import { Route as AppCompanySlugSettingsRouteImport } from './routes/app/$companySlug/settings'
import { Route as CandidateApplicationsApplicationIdRouteImport } from './routes/candidate/applications/$applicationId'
import { Route as CandidateAttemptsAttemptIdRouteImport } from './routes/candidate/attempts/$attemptId'
import { Route as CandidateOffersOfferIdRouteImport } from './routes/candidate/offers/$offerId'
import { Route as CareersCompanySlugIndexRouteImport } from './routes/careers/$companySlug/index'
import { Route as CareersCompanySlugJobSlugRouteImport } from './routes/careers/$companySlug/$jobSlug'
import { Route as AppCompanySlugApplicationsApplicationIdRouteImport } from './routes/app/$companySlug/applications/$applicationId'
import { Route as AppCompanySlugJobsIndexRouteImport } from './routes/app/$companySlug/jobs/index'
import { Route as AppCompanySlugJobsJobIdRouteImport } from './routes/app/$companySlug/jobs/$jobId'
import { Route as AppCompanySlugJobsJobIdPipelineRouteImport } from './routes/app/$companySlug/jobs/$jobId/pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugRouteRoute = AppCompanySlugRouteRouteImport.update({
  id: '/app/$companySlug',
  path: '/app/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderCallbackRoute = ApiProviderCallbackRouteImport.update({
  id: '/api/provider/callback',
  path: '/api/provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanySlugIndexRoute = AppCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugAssessmentsRoute =
  AppCompanySlugAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugAutomationsRoute =
  AppCompanySlugAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugCandidatesRoute =
  AppCompanySlugCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugInterviewsRoute =
  AppCompanySlugInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugOffersRoute = AppCompanySlugOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugReportsRoute = AppCompanySlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugReviewsRoute = AppCompanySlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugSettingsRoute = AppCompanySlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const CandidateApplicationsApplicationIdRoute =
  CandidateApplicationsApplicationIdRouteImport.update({
    id: '/candidate/applications/$applicationId',
    path: '/candidate/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateAttemptsAttemptIdRoute =
  CandidateAttemptsAttemptIdRouteImport.update({
    id: '/candidate/attempts/$attemptId',
    path: '/candidate/attempts/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateOffersOfferIdRoute = CandidateOffersOfferIdRouteImport.update({
  id: '/candidate/offers/$offerId',
  path: '/candidate/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCompanySlugIndexRoute = CareersCompanySlugIndexRouteImport.update({
  id: '/careers/$companySlug/',
  path: '/careers/$companySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCompanySlugJobSlugRoute =
  CareersCompanySlugJobSlugRouteImport.update({
    id: '/careers/$companySlug/$jobSlug',
    path: '/careers/$companySlug/$jobSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCompanySlugApplicationsApplicationIdRoute =
  AppCompanySlugApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppCompanySlugRouteRoute,
  } as any)
const AppCompanySlugJobsIndexRoute = AppCompanySlugJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugJobsJobIdRoute = AppCompanySlugJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppCompanySlugRouteRoute,
} as any)
const AppCompanySlugJobsJobIdPipelineRoute =
  AppCompanySlugJobsJobIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AppCompanySlugJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$companySlug': typeof AppCompanySlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug/': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs/': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/app/$companySlug': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$companySlug': typeof AppCompanySlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/provider/callback': typeof ApiProviderCallbackRoute
  '/app/$companySlug/assessments': typeof AppCompanySlugAssessmentsRoute
  '/app/$companySlug/automations': typeof AppCompanySlugAutomationsRoute
  '/app/$companySlug/candidates': typeof AppCompanySlugCandidatesRoute
  '/app/$companySlug/interviews': typeof AppCompanySlugInterviewsRoute
  '/app/$companySlug/offers': typeof AppCompanySlugOffersRoute
  '/app/$companySlug/reports': typeof AppCompanySlugReportsRoute
  '/app/$companySlug/reviews': typeof AppCompanySlugReviewsRoute
  '/app/$companySlug/settings': typeof AppCompanySlugSettingsRoute
  '/candidate/applications/$applicationId': typeof CandidateApplicationsApplicationIdRoute
  '/candidate/attempts/$attemptId': typeof CandidateAttemptsAttemptIdRoute
  '/candidate/offers/$offerId': typeof CandidateOffersOfferIdRoute
  '/careers/$companySlug/$jobSlug': typeof CareersCompanySlugJobSlugRoute
  '/app/$companySlug/': typeof AppCompanySlugIndexRoute
  '/careers/$companySlug/': typeof CareersCompanySlugIndexRoute
  '/app/$companySlug/applications/$applicationId': typeof AppCompanySlugApplicationsApplicationIdRoute
  '/app/$companySlug/jobs/$jobId': typeof AppCompanySlugJobsJobIdRouteWithChildren
  '/app/$companySlug/jobs/': typeof AppCompanySlugJobsIndexRoute
  '/app/$companySlug/jobs/$jobId/pipeline': typeof AppCompanySlugJobsJobIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/$companySlug'
    | '/invite/$token'
    | '/app/'
    | '/candidate/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/app/$companySlug/'
    | '/careers/$companySlug/'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs/'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/invite/$token'
    | '/app'
    | '/candidate'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/app/$companySlug'
    | '/careers/$companySlug'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/app/$companySlug'
    | '/invite/$token'
    | '/app/'
    | '/candidate/'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/provider/callback'
    | '/app/$companySlug/assessments'
    | '/app/$companySlug/automations'
    | '/app/$companySlug/candidates'
    | '/app/$companySlug/interviews'
    | '/app/$companySlug/offers'
    | '/app/$companySlug/reports'
    | '/app/$companySlug/reviews'
    | '/app/$companySlug/settings'
    | '/candidate/applications/$applicationId'
    | '/candidate/attempts/$attemptId'
    | '/candidate/offers/$offerId'
    | '/careers/$companySlug/$jobSlug'
    | '/app/$companySlug/'
    | '/careers/$companySlug/'
    | '/app/$companySlug/applications/$applicationId'
    | '/app/$companySlug/jobs/$jobId'
    | '/app/$companySlug/jobs/'
    | '/app/$companySlug/jobs/$jobId/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppCompanySlugRouteRoute: typeof AppCompanySlugRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  AppIndexRoute: typeof AppIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiProviderCallbackRoute: typeof ApiProviderCallbackRoute
  CandidateApplicationsApplicationIdRoute: typeof CandidateApplicationsApplicationIdRoute
  CandidateAttemptsAttemptIdRoute: typeof CandidateAttemptsAttemptIdRoute
  CandidateOffersOfferIdRoute: typeof CandidateOffersOfferIdRoute
  CareersCompanySlugJobSlugRoute: typeof CareersCompanySlugJobSlugRoute
  CareersCompanySlugIndexRoute: typeof CareersCompanySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug': {
      id: '/app/$companySlug'
      path: '/app/$companySlug'
      fullPath: '/app/$companySlug'
      preLoaderRoute: typeof AppCompanySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider/callback': {
      id: '/api/provider/callback'
      path: '/api/provider/callback'
      fullPath: '/api/provider/callback'
      preLoaderRoute: typeof ApiProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/': {
      id: '/app/$companySlug/'
      path: '/'
      fullPath: '/app/$companySlug/'
      preLoaderRoute: typeof AppCompanySlugIndexRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/assessments': {
      id: '/app/$companySlug/assessments'
      path: '/assessments'
      fullPath: '/app/$companySlug/assessments'
      preLoaderRoute: typeof AppCompanySlugAssessmentsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/automations': {
      id: '/app/$companySlug/automations'
      path: '/automations'
      fullPath: '/app/$companySlug/automations'
      preLoaderRoute: typeof AppCompanySlugAutomationsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/candidates': {
      id: '/app/$companySlug/candidates'
      path: '/candidates'
      fullPath: '/app/$companySlug/candidates'
      preLoaderRoute: typeof AppCompanySlugCandidatesRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/interviews': {
      id: '/app/$companySlug/interviews'
      path: '/interviews'
      fullPath: '/app/$companySlug/interviews'
      preLoaderRoute: typeof AppCompanySlugInterviewsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/offers': {
      id: '/app/$companySlug/offers'
      path: '/offers'
      fullPath: '/app/$companySlug/offers'
      preLoaderRoute: typeof AppCompanySlugOffersRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/reports': {
      id: '/app/$companySlug/reports'
      path: '/reports'
      fullPath: '/app/$companySlug/reports'
      preLoaderRoute: typeof AppCompanySlugReportsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/reviews': {
      id: '/app/$companySlug/reviews'
      path: '/reviews'
      fullPath: '/app/$companySlug/reviews'
      preLoaderRoute: typeof AppCompanySlugReviewsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/settings': {
      id: '/app/$companySlug/settings'
      path: '/settings'
      fullPath: '/app/$companySlug/settings'
      preLoaderRoute: typeof AppCompanySlugSettingsRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/candidate/applications/$applicationId': {
      id: '/candidate/applications/$applicationId'
      path: '/candidate/applications/$applicationId'
      fullPath: '/candidate/applications/$applicationId'
      preLoaderRoute: typeof CandidateApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/attempts/$attemptId': {
      id: '/candidate/attempts/$attemptId'
      path: '/candidate/attempts/$attemptId'
      fullPath: '/candidate/attempts/$attemptId'
      preLoaderRoute: typeof CandidateAttemptsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/offers/$offerId': {
      id: '/candidate/offers/$offerId'
      path: '/candidate/offers/$offerId'
      fullPath: '/candidate/offers/$offerId'
      preLoaderRoute: typeof CandidateOffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$companySlug/': {
      id: '/careers/$companySlug/'
      path: '/careers/$companySlug'
      fullPath: '/careers/$companySlug/'
      preLoaderRoute: typeof CareersCompanySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$companySlug/$jobSlug': {
      id: '/careers/$companySlug/$jobSlug'
      path: '/careers/$companySlug/$jobSlug'
      fullPath: '/careers/$companySlug/$jobSlug'
      preLoaderRoute: typeof CareersCompanySlugJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$companySlug/applications/$applicationId': {
      id: '/app/$companySlug/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/app/$companySlug/applications/$applicationId'
      preLoaderRoute: typeof AppCompanySlugApplicationsApplicationIdRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/': {
      id: '/app/$companySlug/jobs/'
      path: '/jobs'
      fullPath: '/app/$companySlug/jobs/'
      preLoaderRoute: typeof AppCompanySlugJobsIndexRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/$jobId': {
      id: '/app/$companySlug/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/$companySlug/jobs/$jobId'
      preLoaderRoute: typeof AppCompanySlugJobsJobIdRouteImport
      parentRoute: typeof AppCompanySlugRouteRoute
    }
    '/app/$companySlug/jobs/$jobId/pipeline': {
      id: '/app/$companySlug/jobs/$jobId/pipeline'
      path: '/pipeline'
      fullPath: '/app/$companySlug/jobs/$jobId/pipeline'
      preLoaderRoute: typeof AppCompanySlugJobsJobIdPipelineRouteImport
      parentRoute: typeof AppCompanySlugJobsJobIdRoute
    }
  }
}

interface AppCompanySlugJobsJobIdRouteChildren {
  AppCompanySlugJobsJobIdPipelineRoute: typeof AppCompanySlugJobsJobIdPipelineRoute
}

const AppCompanySlugJobsJobIdRouteChildren: AppCompanySlugJobsJobIdRouteChildren =
  {
    AppCompanySlugJobsJobIdPipelineRoute: AppCompanySlugJobsJobIdPipelineRoute,
  }

const AppCompanySlugJobsJobIdRouteWithChildren =
  AppCompanySlugJobsJobIdRoute._addFileChildren(
    AppCompanySlugJobsJobIdRouteChildren,
  )

interface AppCompanySlugRouteRouteChildren {
  AppCompanySlugAssessmentsRoute: typeof AppCompanySlugAssessmentsRoute
  AppCompanySlugAutomationsRoute: typeof AppCompanySlugAutomationsRoute
  AppCompanySlugCandidatesRoute: typeof AppCompanySlugCandidatesRoute
  AppCompanySlugInterviewsRoute: typeof AppCompanySlugInterviewsRoute
  AppCompanySlugOffersRoute: typeof AppCompanySlugOffersRoute
  AppCompanySlugReportsRoute: typeof AppCompanySlugReportsRoute
  AppCompanySlugReviewsRoute: typeof AppCompanySlugReviewsRoute
  AppCompanySlugSettingsRoute: typeof AppCompanySlugSettingsRoute
  AppCompanySlugIndexRoute: typeof AppCompanySlugIndexRoute
  AppCompanySlugApplicationsApplicationIdRoute: typeof AppCompanySlugApplicationsApplicationIdRoute
  AppCompanySlugJobsJobIdRoute: typeof AppCompanySlugJobsJobIdRouteWithChildren
  AppCompanySlugJobsIndexRoute: typeof AppCompanySlugJobsIndexRoute
}

const AppCompanySlugRouteRouteChildren: AppCompanySlugRouteRouteChildren = {
  AppCompanySlugAssessmentsRoute: AppCompanySlugAssessmentsRoute,
  AppCompanySlugAutomationsRoute: AppCompanySlugAutomationsRoute,
  AppCompanySlugCandidatesRoute: AppCompanySlugCandidatesRoute,
  AppCompanySlugInterviewsRoute: AppCompanySlugInterviewsRoute,
  AppCompanySlugOffersRoute: AppCompanySlugOffersRoute,
  AppCompanySlugReportsRoute: AppCompanySlugReportsRoute,
  AppCompanySlugReviewsRoute: AppCompanySlugReviewsRoute,
  AppCompanySlugSettingsRoute: AppCompanySlugSettingsRoute,
  AppCompanySlugIndexRoute: AppCompanySlugIndexRoute,
  AppCompanySlugApplicationsApplicationIdRoute:
    AppCompanySlugApplicationsApplicationIdRoute,
  AppCompanySlugJobsJobIdRoute: AppCompanySlugJobsJobIdRouteWithChildren,
  AppCompanySlugJobsIndexRoute: AppCompanySlugJobsIndexRoute,
}

const AppCompanySlugRouteRouteWithChildren =
  AppCompanySlugRouteRoute._addFileChildren(AppCompanySlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppCompanySlugRouteRoute: AppCompanySlugRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  AppIndexRoute: AppIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiProviderCallbackRoute: ApiProviderCallbackRoute,
  CandidateApplicationsApplicationIdRoute:
    CandidateApplicationsApplicationIdRoute,
  CandidateAttemptsAttemptIdRoute: CandidateAttemptsAttemptIdRoute,
  CandidateOffersOfferIdRoute: CandidateOffersOfferIdRoute,
  CareersCompanySlugJobSlugRoute: CareersCompanySlugJobSlugRoute,
  CareersCompanySlugIndexRoute: CareersCompanySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
